### login
POST {{host-url}}/login
Content-Type: application/json

{
  "username": "customer1@email.com",
  "password": "123",
  "rem": true
}

### register
POST {{host-url}}/register
Content-Type: application/json

{
  "email": "user2@gmail.com",
  "password": "123",
  "name": "userTest3",
  "phone": "12345",
  "address": "address",
  "active": true
}

### get user's cart
GET {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

[
]

###
PUT {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

3

### add user's cart
POST {{host-url}}/cart/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 4,
  "productId": "B0002"
}

### cart checkout
POST {{host-url}}/cart/checkout
Content-Type: application/json
Authorization: Bearer {{token}}

### get order by id
GET {{host-url}}/order/2
Authorization: Bearer {{token}}

### finish order
PATCH {{host-url}}/order/finish/2147483641
Authorization: Bearer {{token}}


### get product

GET {{host-url}}/product/B0003

Content-Type: application/json
Authorization: Bearer {{token}}

### edit product

PUT {{host-url}}/seller/product/B0002/edit
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "B0002",
  "productName": "Spring In Action",
  "productPrice": 26.00,
  "productStock": 195,
  "productDescription": "Learn Spring",
  "productIcon": "https://images-na.ssl-images-amazon.com/images/I/51gHy16h5TL._SX397_BO1,204,203,200_.jpg",
  "productStatus": 1,
  "categoryType": 0,
  "updateTime": "2019-01-05T03:43:29.047+0000"
}

### add new product

POST {{host-url}}/seller/product/new
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "productId": "B0022",
  "productName": "Spring In Action",
  "productPrice": 20.00,
  "productStock": 195,
  "productDescription": "Learn Spring",
  "productIcon": "https://images-na.ssl-images-amazon.com/images/I/51gHy16h5TL._SX397_BO1,204,203,200_.jpg",
  "productStatus": 0,
  "categoryType": 1
}

### delete product

DELETE {{host-url}}/seller/product/B0003/delete
Content-Type: application/json
Authorization: Bearer {{token}}
