POST {{host-url}}/login
Content-Type: application/json

{
  "username": "customer1@email.com",
  "password": "123",
  "rem": true
}
###
POST {{host-url}}/register
Content-Type: application/json

{
  "email": "user1@gmail.com",
  "password": "12345",
  "name": "userTest3",
  "phone": "12345",
  "address": "address",
  "active": true
}

### get user's cart
GET {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

###
POST {{host-url}}/cart
Content-Type: application/json
Authorization: Bearer {{token}}

[
]

###
PUT {{host-url}}/cart/B0002
Content-Type: application/json
Authorization: Bearer {{token}}

3

### add user's cart
POST {{host-url}}/cart/add
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "quantity": 1,
  "productId": "B0002"
}

