
server:
  port: 9337
  servlet:
    context-path: /api/
    # http://localhost:9337/api
#spring:
#  application:
#    name: USER-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/testdb3
#    username: root
#    password: 12345
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
#    hibernate:
#      ddl-auto: update  # create

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/testdb3
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    username: root
#    password: 123456
#    platform: h2
#    url: jdbc:h2:mem:jwt-demo
#  h2:
#    console:
#      enabled: true
#      settings:
#        web-allow-others: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    open-in-view: false
#    properties:
#      hibernate:
#        enable_lazy_load_no_trans: true
#    show-sql: false
#  cache:
#    # ???Spring Cache?????spring.cache.type???????????????????Cache???????????Redis??????JCache -> EhCache -> Redis -> Guava?
#    type: REDIS
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    # password:  ??????????????????
#    # ???????ms?
#    timeout: 10000
#    # Redis??????16???????????????????0
#    database: 0
#    jedis:
#      pool:
#        # ???????????????????? ?? 8
#        max-active: 10
#        # ??????????????????????? ?? -1
#        max-wait: -1
#        # ??????????? ?? 8
#        max-idle: 8
#        # ??????????? ?? 0
#        min-idle: 0
