#server:
#  port: 8080
#
#spring:
#  thymeleaf:
#    cache: false
#  datasource:
#    url: jdbc:mysql://localhost:3306/security00?useUnicode=true&characterEncoding=utf8mb4
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: Passw0rd
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5Dialect


server:
  port: 9991

#spring:
#  thymeleaf:
#    cache: false

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/a_mymall
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update